### ISSUE TITLE
README is not clear about docker config

### ISSUE THREAD

**Issue by mickaelperrin** [ShiraNai7/phpstorm-docker-proxy#1]
Hi,

I give a try to your project but don't understand if I need ton indicate the name of a docker image or a docker container in the config file.

> change php_image_name_here to the name of your project's PHP Docker **image** (i.e. an **image** that contains a php binary executable from CLI)

then

> make sure the **container** specified in the configuration is up and running

**Comment by mickaelperrin** [comment]
I got it working by specifiying an image name.

But question, how do you handle multiple containers running at the same time and using the same image ?

**Comment by shira-374** [comment]
That's currently not handled. I can add support for using container names instead of image names.

**Comment by mickaelperrin** [comment]
Thanks I pushed #4 related to this issue. Maybe you could have a look at it?
